Repository woowa-techcamp-2022/android-repo-10, pull requests merged in 2022-07, with the labels that each got.

#6 아이콘, 색상, 배경 기초 세팅
  app/src/main/java/com/github/repo/MainActivity.kt
  app/src/main/res/drawable/btn_active_14dp.xml
  app/src/main/res/drawable/btn_deactive_14dp.xml
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_bookmark.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/drawable/ic_issue_closed.xml
  app/src/main/res/drawable/ic_issue_open.xml
  app/src/main/res/drawable/ic_link.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_mail.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_bold.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/ic_title.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/ic_users.xml
  app/src/main/res/drawable/ic_variant10.xml
  app/src/main/res/drawable/ic_variant16.xml
  app/src/main/res/font-v26/app_font.xml
  app/src/main/res/font/app_font.xml
  app/src/main/res/font/ko_pub_world_dotum_pro_bold.otf
  app/src/main/res/font/ko_pub_world_dotum_pro_light.otf
  app/src/main/res/font/ko_pub_world_dotum_pro_medium.otf
  app/src/main/res/font/outfit_semi_bold.ttf
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: ui

#12 gradle 버전 관리
  app/build.gradle
  app/build.gradle.kts
  app/proguard-rules.pro
  build.gradle
  build.gradle.kts
  buildSrc/.gitignore
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/AppConfig.kt
  buildSrc/src/main/java/Dependencies.kt
  settings.gradle.kts
Labels: feature

#15 배경색 그라데이션 적용
  app/src/main/res/drawable/background_main.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: ui, fix, 태우, 주호

#16 메인 화면 공통 app bar 레이아웃 생성
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ui, 태우, 주호

#18 선정된 라이브러리 추가
  app/build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: feature

#20 Koin 의존성 주입 적용
  app/src/main/java/com/github/repo/application/GithubRepositoryApplication.kt
Labels: feature

#22 메인 화면 공통 app bar 기능 구현
  app/src/main/java/com/github/repo/presentation/main/MainActivity.kt
  app/src/main/java/com/github/repo/presentation/profile/ProfileFragment.kt
  app/src/main/java/com/github/repo/presentation/search/SearchFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature, 태우, 주호

#28 메인 화면 공통 버튼 및 Issue, Notifications UI 생성
  app/src/main/java/com/github/repo/presentation/main/issue/IssueFragment.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsFragment.kt
  app/src/main/res/drawable/btn_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/fragment_notifications.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ui, 태우, 주호

#30 main 공통 버튼 변경
  app/src/main/res/layout/activity_main.xml
Labels: ui, fix, 태우, 주호

#32 메인 화면 버튼 기능 구현 및 현재 프래그먼트에 따른 백버튼 동작 구현
  app/src/main/java/com/github/repo/presentation/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: feature, 태우, 주호

#34 커스텀 툴바 생성
  app/src/main/java/com/github/repo/presentation/common/CustomToolbar.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/view_toolbar.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: ui, 태우

#35 Notification 화면 레이아웃 및 RecyclerView Item 레이아웃 생성
  app/src/main/res/layout/fragment_notifications.xml
  app/src/main/res/layout/item_notification.xml
Labels: ui, 주호

#43 notification api 요청 구현 및 RecyclerVIew 설정
  app/src/main/java/com/github/repo/data/datasource/GithubDataSource.kt
  app/src/main/java/com/github/repo/data/dto/GithubNotificationDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubOwnerDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubSubjectDto.kt
  app/src/main/java/com/github/repo/data/dto/Repository.kt
  app/src/main/java/com/github/repo/data/network/GitHubService.kt
  app/src/main/java/com/github/repo/data/repository/GithubRepositoryImpl.kt
  app/src/main/java/com/github/repo/di/DataSoruceModel.kt
  app/src/main/java/com/github/repo/di/NetworkModule.kt
  app/src/main/java/com/github/repo/di/RepositoryModule.kt
  app/src/main/java/com/github/repo/di/ViewModelModule.kt
  app/src/main/java/com/github/repo/di/provideAPI.kt
  app/src/main/java/com/github/repo/domain/dto/NotificationDto.kt
  app/src/main/java/com/github/repo/domain/repository/GithubRepository.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsFragment.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsViewModel.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/UiState.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/adapter/NotificationAdapter.kt
  app/src/main/java/com/github/repo/utils/DateUtils.kt
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature, fix, 주호

#42 검색 화면 및 기능 구현
  app/build.gradle.kts
  app/src/main/java/com/github/repo/data/datasource/GithubDataSource.kt
  app/src/main/java/com/github/repo/data/dto/GithubOwnerDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubRepoDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubSearchDto.kt
  app/src/main/java/com/github/repo/data/network/GitHubService.kt
  app/src/main/java/com/github/repo/data/repository/GithubRepositoryImpl.kt
  app/src/main/java/com/github/repo/di/ViewModelModule.kt
  app/src/main/java/com/github/repo/domain/model/GithubOwner.kt
  app/src/main/java/com/github/repo/domain/model/GithubRepo.kt
  app/src/main/java/com/github/repo/domain/model/GithubSearch.kt
  app/src/main/java/com/github/repo/domain/model/Language.kt
  app/src/main/java/com/github/repo/domain/repository/GithubRepository.kt
  app/src/main/java/com/github/repo/presentation/common/Clickable.kt
  app/src/main/java/com/github/repo/presentation/common/CustomToolbar.kt
  app/src/main/java/com/github/repo/presentation/common/GlideModule.kt
  app/src/main/java/com/github/repo/presentation/common/ImageViewBindingAdpaters.kt
  app/src/main/java/com/github/repo/presentation/common/TextViewBindingAdpaters.kt
  app/src/main/java/com/github/repo/presentation/login/LoginActivity.kt
  app/src/main/java/com/github/repo/presentation/main/MainActivity.kt
  app/src/main/java/com/github/repo/presentation/main/issue/IssueFragment.kt
  app/src/main/java/com/github/repo/presentation/profile/ProfileFragment.kt
  app/src/main/java/com/github/repo/presentation/search/SearchFragment.kt
  app/src/main/java/com/github/repo/presentation/search/SearchViewModel.kt
  app/src/main/java/com/github/repo/presentation/search/UiState.kt
  app/src/main/java/com/github/repo/presentation/search/adapter/RepositoryAdapter.kt
  app/src/main/res/drawable/btn_deactive_focus_14dp.xml
  app/src/main/res/drawable/edittext_background.xml
  app/src/main/res/drawable/ic_purple.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/recylerview_divider.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_repository.xml
  app/src/main/res/values-night-v23/strings.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: feature, ui, 태우

#47 Swipe UI 레이아웃 만들기
  app/src/main/res/layout/item_notification.xml
Labels: ui, 주호

#50 Notification Swipe Guesture 기능 처리
  app/src/main/java/com/github/repo/data/datasource/GithubDataSource.kt
  app/src/main/java/com/github/repo/data/dto/GithubAssigneeDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubCreatorDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubIssueDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubLabelDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubMilestoneDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubNotificationDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubOwnerDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubReactionsDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubRepositoryDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubSubjectDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubTokenDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubUserDto.kt
  app/src/main/java/com/github/repo/data/network/GitHubService.kt
  app/src/main/java/com/github/repo/data/repository/GithubRepositoryImpl.kt
  app/src/main/java/com/github/repo/domain/model/Notification.kt
  app/src/main/java/com/github/repo/domain/repository/GithubRepository.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsFragment.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsViewModel.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/UiState.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/adapter/NotificationAdapter.kt
  app/src/main/res/layout/item_notification.xml
Labels: feature, 주호

#48 검색화면 키보드 컨트롤
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/repo/presentation/login/LoginActivity.kt
  app/src/main/java/com/github/repo/presentation/main/MainActivity.kt
  app/src/main/java/com/github/repo/presentation/search/SearchFragment.kt
  app/src/main/java/com/github/repo/presentation/search/SearchViewModel.kt
  app/src/main/res/drawable/edittext_background.xml
  app/src/main/res/layout/fragment_search.xml
Labels: feature, 태우

#51 Notification 에러 해결
  app/src/main/java/com/github/repo/data/datasource/GithubDataSource.kt
  app/src/main/java/com/github/repo/data/network/GitHubService.kt
  app/src/main/java/com/github/repo/data/repository/GithubRepositoryImpl.kt
  app/src/main/java/com/github/repo/domain/repository/GithubRepository.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsViewModel.kt
Labels: fix, 태우, 주호

#53 Notification 데이터 로드 실패 개선
  app/src/main/java/com/github/repo/data/dto/GithubIssueDto.kt
Labels: fix, 태우

#56 Notification에서 comment 정보 가져오기 개선
  app/src/main/java/com/github/repo/data/network/GitHubService.kt
  app/src/main/java/com/github/repo/data/repository/GithubRepositoryImpl.kt
Labels: 태우, refactor

#58 UiState 일반화
  app/src/main/java/com/github/repo/presentation/common/UiState.kt
  app/src/main/java/com/github/repo/presentation/login/LoginActivity.kt
  app/src/main/java/com/github/repo/presentation/login/LoginViewModel.kt
  app/src/main/java/com/github/repo/presentation/login/UiState.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsFragment.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsViewModel.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/UiState.kt
  app/src/main/java/com/github/repo/presentation/search/SearchFragment.kt
  app/src/main/java/com/github/repo/presentation/search/SearchViewModel.kt
  app/src/main/java/com/github/repo/presentation/search/UiState.kt
Labels: 태우, refactor

#64 이슈 화면 구성 및 기능 구현
  app/src/main/java/com/github/repo/data/datasource/GithubDataSource.kt
  app/src/main/java/com/github/repo/data/dto/GithubIssueDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubLicenseDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubPermissionsDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubPullRequestDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubRepoDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubRepositoryDto.kt
  app/src/main/java/com/github/repo/data/network/GitHubService.kt
  app/src/main/java/com/github/repo/data/repository/GithubRepositoryImpl.kt
  app/src/main/java/com/github/repo/di/RepositoryModule.kt
  app/src/main/java/com/github/repo/di/ViewModelModule.kt
  app/src/main/java/com/github/repo/domain/model/GithubIssue.kt
  app/src/main/java/com/github/repo/domain/model/GithubRepo.kt
  app/src/main/java/com/github/repo/domain/model/Notification.kt
  app/src/main/java/com/github/repo/domain/repository/GithubRepository.kt
  app/src/main/java/com/github/repo/presentation/common/ImageViewBindingAdpaters.kt
  app/src/main/java/com/github/repo/presentation/main/issue/IssueFragment.kt
  app/src/main/java/com/github/repo/presentation/main/issue/IssueViewModel.kt
  app/src/main/java/com/github/repo/presentation/main/issue/OptionType.kt
  app/src/main/java/com/github/repo/presentation/main/issue/adapter/IssueAdapter.kt
  app/src/main/java/com/github/repo/presentation/main/issue/adapter/SpinnerAdapter.kt
  app/src/main/res/drawable/checkbox_custom.xml
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/item_issue.xml
  app/src/main/res/layout/item_spinner_content.xml
  app/src/main/res/layout/item_spinner_title.xml
  app/src/main/res/values-night-v23/strings.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature, ui, 태우

#66 profile starred 데이터 로드 해결
  app/src/main/java/com/github/repo/data/datasource/GithubDataSource.kt
  app/src/main/java/com/github/repo/data/network/GitHubService.kt
  app/src/main/java/com/github/repo/data/repository/GithubRepositoryImpl.kt
Labels: fix, 태우, 주호

#67 feat: toolbar 프로필 이미지 로딩
  app/src/main/java/com/github/repo/presentation/main/MainActivity.kt
  app/src/main/java/com/github/repo/presentation/profile/ProfileFragment.kt
  app/src/main/res/layout/activity_main.xml
Labels: feature, ui, 태우, 주호

#69 configuration change 대응
  app/src/main/java/com/github/repo/presentation/main/MainActivity.kt
  app/src/main/java/com/github/repo/presentation/main/issue/IssueFragment.kt
  app/src/main/java/com/github/repo/presentation/profile/ProfileViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: fix, 태우

#71 API요청의 헤더 정리
  app/src/main/java/com/github/repo/config/XAccessTokenInterceptor.kt
  app/src/main/java/com/github/repo/data/datasource/GithubDataSource.kt
  app/src/main/java/com/github/repo/data/network/GitHubService.kt
  app/src/main/java/com/github/repo/data/repository/GithubRepositoryImpl.kt
  app/src/main/java/com/github/repo/di/NetworkModule.kt
  app/src/main/java/com/github/repo/di/ViewModelModule.kt
  app/src/main/java/com/github/repo/di/provideAPI.kt
  app/src/main/java/com/github/repo/domain/repository/GithubRepository.kt
  app/src/main/java/com/github/repo/presentation/main/issue/IssueViewModel.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsViewModel.kt
  app/src/main/java/com/github/repo/presentation/profile/ProfileViewModel.kt
Labels: feature, 주호, refactor

#74 알림 스와이프 클래스 분리
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsFragment.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/SwipeHelperCallback.kt
Labels: 태우, refactor

#75 무한 스크롤 처리
  app/src/main/java/com/github/repo/config/XAccessTokenInterceptor.kt
  app/src/main/java/com/github/repo/data/datasource/GithubDataSource.kt
  app/src/main/java/com/github/repo/data/dto/GithubIssueDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubOrganizationDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubStarredDto.kt
  app/src/main/java/com/github/repo/data/network/GitHubService.kt
  app/src/main/java/com/github/repo/data/repository/GithubRepositoryImpl.kt
  app/src/main/java/com/github/repo/domain/model/Profile.kt
  app/src/main/java/com/github/repo/domain/repository/GithubRepository.kt
  app/src/main/java/com/github/repo/presentation/common/RecyclerViewScrollMediator.kt
  app/src/main/java/com/github/repo/presentation/main/issue/IssueFragment.kt
  app/src/main/java/com/github/repo/presentation/main/issue/IssueViewModel.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsFragment.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/NotificationsViewModel.kt
  app/src/main/java/com/github/repo/presentation/profile/custom/CustomProfileUserInfoItem.kt
  app/src/main/java/com/github/repo/presentation/search/SearchFragment.kt
  app/src/main/java/com/github/repo/presentation/search/SearchViewModel.kt
Labels: feature, 태우

#77 github에서 받아온 시간을 timezone을 변경
  app/src/main/java/com/github/repo/utils/DateUtils.kt
Labels: fix, 주호

#78 알림 비동기 코드 코드 개선
  app/src/main/java/com/github/repo/data/repository/GithubRepositoryImpl.kt
Labels: 태우, refactor

#82 Repository 코드 개선
  app/src/main/java/com/github/repo/data/dto/GithubIssueDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubLicenseDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubRepoDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubRepositoryDto.kt
  app/src/main/java/com/github/repo/data/dto/GithubSearchDto.kt
  app/src/main/java/com/github/repo/data/network/GitHubService.kt
  app/src/main/java/com/github/repo/domain/model/GithubIssue.kt
  app/src/main/java/com/github/repo/domain/model/GithubRepository.kt
  app/src/main/java/com/github/repo/domain/model/GithubSearch.kt
  app/src/main/java/com/github/repo/presentation/common/Constant.kt
  app/src/main/java/com/github/repo/presentation/search/SearchViewModel.kt
  app/src/main/java/com/github/repo/presentation/search/adapter/RepositoryAdapter.kt
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/layout/item_repository.xml
Labels: 태우, refactor

#83 잘못된 바인딩 개선
  app/src/main/java/com/github/repo/utils/DateUtils.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_issue.xml
  app/src/main/res/layout/item_notification.xml
Labels: 태우, refactor

#85 시간 포맷팅 개선
  app/src/main/java/com/github/repo/presentation/main/issue/adapter/IssueAdapter.kt
  app/src/main/java/com/github/repo/presentation/main/notifications/adapter/NotificationAdapter.kt
  app/src/main/java/com/github/repo/utils/DateUtils.kt
Labels: 태우, refactor
